### ISSUE TITLE
Example 3.3 Galileo and uniform acceleration

### ISSUE THREAD

**Issue by AKJ7** [neonwatty/machine-learning-refined#15]
Hello sir,

i was trying to solve Exercice 3.4: Reproduce Galileo's Example, which meant reproducing the graph of Example 3.3, and got w=0.0196, which should be the earth gravity: g=9.81 m/s^2. Since i was able reproduce the requested graphs, i suppose that w is correct, but was wondering why it doesn't match g. What are the units of the input values?

Thank you.

**Comment by RezaBorhani** [comment]
@AKJ7 The data in that example was taken from the following paper wherein the authors attempted to reenact the Galileo’s ramp experiment with the kind of tools available at his time. For example, they used a water clock — just as Galileo did — to measure time, and because of that time here is given in milliliters of fallen water (as a proxy for seconds). See the original paper below for more information.

[Reconstruction of Galileo Galilei's experiment: the inclined plane](https://iopscience.iop.org/article/10.1088/0031-9120/43/3/012)
