### ISSUE TITLE
Problems with the electronic version on Amazon

### ISSUE THREAD

**Issue by ramtob** [neonwatty/machine-learning-refined#18]
Two major issues with the electronic version of the book on Amazon. 

1. The electronic version is a PDF file, not MOBI. In other words, it has not been adapted to Amazon Kindle.
    In particular, links in the text don't work, from Kindle. And the contents menu is static, not hypertext.

2. Some of the materials on the HTML pages / notebooks just don't exist in the Amazon PDF version. The opposite of what I expected! (because each of your HTML pages / notebooks contains this insert: "The following is part of an *early draft* of the second edition of Machine Learning Refined. The published text (with *revised material*) is now available on Amazon"). For example, sections 6.2 and 6.3 in the HTML pages contain appendixes with proofs. These appendixes do not exist in the Amazon PDF version.

Can these problems be fixed? TIA

**Comment by neonwatty** [comment]
My apologies for the delayed response!   I am very sorry to hear that you find the electronic version of the text unsatisfactory.  

As to the issues with the electronic version of the text:

On issue #1 - we have been in contact with the Press regarding issues with the electronic version of the text.  A MOBI was originally released on Amazon, but due to quality issues  (typesetting / rendering of equations - that - at least up to present - cannot be adequately dealt with) we recurred to the PDF format as the better (but suboptimal) choice. 

On issue #2 - I hear your concerns.  Some mathematical proofs - present in these drafts but deemed of lower importance in the final publication - were removed due to printing length considerations .  However almost all of the overlap material present in both these drafts and the published text underwent considerable polishing prior to publishing, and in some cases complete rewriting.   In addition, Chapters 1, 12, 14, Appendix B, and a large swath of Sections throughout most Chapters were not available as drafts.  So I do believe that we provided significantly more in the final product than in the drafts maintained here.

However all of this being said, if you are unhappy with your purchase of the e-text I would be happy to provide full refund of your purchase - please email me at jermwatt@gmail.com and we can get this started.

**Comment by ramtob** [comment]
@jermwatt 

Thanks for replying. I already cancelled my purchase at Amazon, so refund is not an issue at this point. I hope a MOBI version can be produced at some point, because reading a PDF on Kindle is possible but awkward and uncomfortable. Thanks anyway for your excellent book.
